// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package querytest

import (
	"context"
	"database/sql"
)

type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

func NewRead(db DBTX) *Read {
	return &Read{db: db}
}

type Read struct {
	db DBTX
}

func (q *Read) WithTx(tx *sql.Tx) *Read {
	return &Read{
		db: tx,
	}
}

func NewWrite(db DBTX) *Write {
	return &Write{db: db}
}

type Write struct {
	db DBTX
}

func (q *Write) WithTx(tx *sql.Tx) *Write {
	return &Write{
		db: tx,
	}
}
