// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: read.sql

package querytest

import (
	"context"
)

const listFoo = `-- name: ListFoo :many
SELECT id, bar FROM foo
`

func (q *Read) ListFoo(ctx context.Context) ([]Foo, error) {
	rows, err := q.db.QueryContext(ctx, listFoo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Foo
	for rows.Next() {
		var i Foo
		if err := rows.Scan(&i.ID, &i.Bar); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
