// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: write.sql

package querytest

import (
	"context"
)

const createFoo = `-- name: CreateFoo :one
INSERT INTO foo (bar) VALUES ($1) RETURNING id, bar
`

func (q *Write) CreateFoo(ctx context.Context, bar string) (Foo, error) {
	row := q.db.QueryRowContext(ctx, createFoo, bar)
	var i Foo
	err := row.Scan(&i.ID, &i.Bar)
	return i, err
}
